### PR TITLE
Update shoelace to 1.0.4

### PR DESCRIPTION
**Pull request by CrookedGrin**
## Ticket
[Notion](url)

## Release Reminder (delete before submitting PR)
*Consider whether or not you'll need to manually redeploy any consuming apps (e.g. Buyout, OS) as soon as this change is merged.*

**Reminder:** these changes won't be pulled into any downstream apps until you merge _this_ PR, and _then_ merge a PR _on that app_ checking in an updated `yarn.lock` (i.e. after having run `yarn upgrade @teamshares/ui`).

### CODE REVIEW

**Review by kdonovan — CHANGES_REQUESTED** [review]
I _think_ you also need to run `yarn install`, and then check in an updated `yarn.lock`? I missed that step last time and had to add it manually later...

**Comment by CrookedGrin** [comment]
> 
Good call, Kali. I was trying to do it through the GitHub web UI, but that doesn't work by itself.

**Review by kdonovan — APPROVED** [review]
Awesome, looks great! 🚗

**Comment by kdonovan** [comment]
Handled [by renovate](https://github.com/teamshares/shared-ui/pull/125) :)

**Pull request closed without merging**
